/**
 * Concept glossary.
 *
 * Every entry is anchored to the reference material in /reference/scaling-book/.
 * `sourceRef` points at the file + section so the UI can cite the source.
 */

export interface Concept {
  id: string;
  title: string;
  summary: string;
  body: string[];
  formula?: string;
  sourceRef: string;
  related: string[];
}

export const CONCEPTS: Concept[] = [
  {
    id: 'flops',
    title: 'FLOPs & Compute',
    summary: 'How much arithmetic an operation needs, measured in floating-point operations per second (FLOPs/s).',
    body: [
      'A deep learning model is effectively a stack of matrix multiplications. Each multiply-and-add is one "floating-point operation" (FLOP), and your accelerator\'s FLOPs/s rating decides how long the math takes.',
      'The time to do the math is T_math = (FLOPs) / (FLOPs/s). A matmul X[B,D]·Y[D,F]→Z[B,F] needs 2·B·D·F FLOPs.',
      'Note that accelerators rarely hit their headline number: GPUs typically achieve ~80-85% of claimed peak, TPUs closer to 95%.',
      'Reference numbers: an H100 sustains ≈9.89e14 bf16 FLOPs/s, a TPU v6e ≈9.1e14, a TPU v5e ≈1.97e14. int8 roughly doubles this (TPU v5e ≈3.94e14, H100 fp8 ≈2.0e15); fp4 doubles it again.',
      'Per-chip figures hide the core structure: TPU v5p is ≈2.5e14 bf16 FLOPs/s per core or ≈5e14 per chip (two cores in a megacore), and a full 8,960-chip v5p pod sustains ~4 bf16 exaFLOPs/s.',
      'For cost modeling, remember the token-level figure: training is roughly 6·N FLOPs per token, while a forward/inference pass is 2·N — the difference is the backward pass (see "FLOPs per Token").',
    ],
    formula: 'T_math = (Computation FLOPs) / (Accelerator FLOPs/s)',
    sourceRef: 'reference/scaling-book/roofline.md — "Where Does the Time Go?" · reference/scaling-book/tpus.md — "What Is a TPU?"',
    related: ['matmul-intensity', 'arithmetic-intensity', 'roofline', 'mfu', 'flops-per-token', 'tpu-architecture'],
  },
  {
    id: 'bandwidth',
    title: 'Memory Bandwidth',
    summary: 'How fast data can move between accelerator memory (HBM) and the compute cores, in bytes/s.',
    body: [
      'Tensors must be transferred between accelerator memory and the compute cores. The speed of this link is the HBM / memory bandwidth.',
      'The time to move the data is T_comms = (Bytes) / (Bandwidth). On an H100 that bandwidth is ≈3.35 TB/s; on a TPU v6e it is ≈1.6 TB/s.',
      'This is the "memory wall": when an operation is limited by moving bytes rather than doing math, we say it is memory- or bandwidth-bound.',
      'HBM on the accelerator is large (tens of GB) but relatively slow (~1-2 TB/s). On-chip memory (VMEM/SMEM) is much smaller yet ~22x higher bandwidth — so the same weight can stream from either, at very different achievable intensity.',
      'Bandwidth is a hierarchy, not a single number: on-chip HBM (~1-2 TB/s) > inter-chip ICI (~90 GB/s per axis) > PCIe (~16 GB/s) > data-center DCN (~6.25 GB/s). The roofline you care about uses whichever link the data actually crosses.',
      'During generation each decode step reloads the full parameter set from HBM, which is exactly why generation is bandwidth-bound; see "Memory Hierarchy".',
    ],
    formula: 'T_comms = (Communication Bytes) / (Bandwidth Bytes/s)',
    sourceRef: 'reference/scaling-book/roofline.md — "Where Does the Time Go?" · reference/scaling-book/tpus.md — "TPU Networking"',
    related: ['memory-bound', 'roofline', 'flops', 'memory-hierarchy', 'tpu-networking'],
  },
  {
    id: 'arithmetic-intensity',
    title: 'Arithmetic Intensity',
    summary: 'The ratio of FLOPs to bytes moved — the "FLOPs per byte" of an operation.',
    body: [
      'Arithmetic intensity measures how much math you get out of every byte you drag through memory: I = (Total FLOPs) / (Total Bytes).',
      'High intensity means math dominates and you use most of the accelerator; low intensity means bytes dominate and you waste FLOPs waiting for data.',
      'It is the single most useful number in roofline analysis — it tells you which side of the ridge an operation sits on.',
      'There is a direct equivalence: the operation is compute-bound iff T_math ≥ T_comms, which happens exactly when I (operation) ≥ I_hw (hardware ridge).',
      'Different on-chip units have different ridges: the matrix unit (MXU/Tensor Core) is ≈240 FLOPs/byte from HBM, while the vector unit (VPU) has a far lower peak, so an elementwise op can be bandwidth-bound even where a matmul is not.',
    ],
    formula: 'I = (Computation FLOPs) / (Communication Bytes)',
    sourceRef: 'reference/scaling-book/roofline.md — "Where Does the Time Go?"',
    related: ['roofline', 'ridge-point', 'compute-bound', 'memory-bound', 'matmul-intensity', 'tiling'],
  },
  {
    id: 'roofline',
    title: 'The Roofline',
    summary: 'A log-log plot of achievable FLOPs/s vs arithmetic intensity, showing where an operation hits the bandwidth or compute ceiling.',
    body: [
      'The roofline plots peak achievable FLOPs/s (throughput, y-axis) against arithmetic intensity (x-axis).',
      'At low intensity you are limited by memory bandwidth, so throughput grows linearly with intensity; past the ridge you saturate peak FLOPs/s.',
      'An operation sits either on the sloped "bandwidth roof" or on the flat "compute roof" — the max of the two bounds is the roofline.',
      'Hardware is bounded by three things: how fast it does math, its bandwidth for moving data, and its total memory.',
      'Reading the plot: left of the ridge the achievable FLOPs/s rises linearly with intensity (the sloped "bandwidth roof"); past the ridge it flattens at peak (the "compute roof"). Raising intensity OR raising bandwidth moves an op toward the peak.',
      'The same roofline idea applies at chip level (HBM bandwidth vs math) and at cluster level (inter-chip network vs math) — the only difference is which bandwidth you plug in.',
    ],
    formula: 'Throughput = min(Bandwidth × Intensity, Peak FLOPs/s)',
    sourceRef: 'reference/scaling-book/roofline.md — "Visualizing rooflines"',
    related: ['ridge-point', 'arithmetic-intensity', 'compute-bound', 'memory-bound'],
  },
  {
    id: 'ridge-point',
    title: 'Ridge Point',
    summary: 'The arithmetic intensity at which an accelerator saturates its FLOPs/s — the crossover from bandwidth-bound to compute-bound.',
    body: [
      'The ridge point is the ratio of peak accelerator FLOPs/s to memory bandwidth: I_hw = (Peak FLOPs/s) / (Bandwidth).',
      'For a TPU v5e MXU this is ≈240 FLOPs/byte; for an H100 it is ≈295 FLOPs/byte.',
      'GPUs land slightly above TPUs: H100 ≈295, B200 (Blackwell) ≈281, both around ~300. Lower precision changes the ridge: fp8 roughly doubles peak intensity (H100 ≈590, B200 ≈562), so the ridge moves right.',
      'Left of the ridge you are bandwidth-bound; right of it you are compute-bound and use the accelerator fully.',
    ],
    formula: 'I_hw = (Peak FLOPs/s) / (Bandwidth Bytes/s)',
    sourceRef: 'reference/scaling-book/roofline.md — "Where Does the Time Go?"',
    related: ['roofline', 'critical-batch', 'compute-bound', 'memory-bound'],
  },
  {
    id: 'compute-bound',
    title: 'Compute-Bound',
    summary: 'When an operation is limited by math speed: intensity above the ridge, FLOPs/s fully utilized.',
    body: [
      'When T_math ≥ T_comms the operation is compute-bound — you use essentially all the accelerator\'s FLOPs/s.',
      'This is the good regime for a server: you are not wasting arithmetic throughput.',
      'For a bf16 matmul this happens when the per-replica token batch B is above the critical batch size.',
    ],
    sourceRef: 'reference/scaling-book/roofline.md — "Where Does the Time Go?"',
    related: ['ridge-point', 'critical-batch', 'roofline'],
  },
  {
    id: 'memory-bound',
    title: 'Memory-Bound',
    summary: 'When an operation is limited by moving bytes: intensity below the ridge, FLOPs left on the table.',
    body: [
      'When T_comms > T_math the operation is memory- (bandwidth-, comms-) bound — some fraction of your FLOPs/s is wasted waiting for data.',
      'This is the normal regime for transformer generation: a single decode token streams the whole parameter set, so bytes dominate.',
      'Batching more requests together pushes per-token intensity back toward the ridge.',
    ],
    sourceRef: 'reference/scaling-book/roofline.md — "Where Does the Time Go?"',
    related: ['generation', 'ridge-point', 'bandwidth'],
  },
  {
    id: 'overlap',
    title: 'Lower vs Upper Bound',
    summary: 'Math and communication can overlap, so the run time sits between the max and the sum of T_math and T_comms.',
    body: [
      'Computation within/on a chip can usually be overlapped with communication, so we lower-bound time by the max of the two, and upper-bound by their sum.',
      'Because T_math + T_comms ≤ 2·max(T_math, T_comms), the two bounds differ by at most 2× — this is the room available for overlap optimizations.',
      'When T_math ≈ T_comms the overlap wins the most, which is why collective matmuls are valuable.',
    ],
    formula: 'T_lower = max(T_math, T_comms) · T_upper = T_math + T_comms',
    sourceRef: 'reference/scaling-book/roofline.md — "Where Does the Time Go?"',
    related: ['roofline', 'arithmetic-intensity'],
  },
  {
    id: 'matmul-intensity',
    title: 'Matmul Intensity & the B Rule',
    summary: 'A matmul\'s intensity is ≈ its token batch size B, so "compute-bound iff B > critical batch".',
    body: [
      'For X[B,D]·Y[D,F]→Z[B,F], the intensity is I = 2BDF / (2BD + 2DF + 2BF).',
      'When B is small relative to D and F (typical: B < 1024 tokens, D,F > 8000), this simplifies to I ≈ B.',
      'So a bf16 matmul becomes compute-bound iff B > I_hw ≈ 240 tokens on most TPUs, ≈295 on an H100. A very simple rule!',
      'This B is a per-replica token batch (tokens, not sequences).',
      'Caveat from tiling: a real matmul is decomposed into tiles that fit on-chip memory, so bytes exceed the naive O(N²) estimate and effective intensity ≈ bm·bn/(bm+bn) — tuning tile sizes also tunes intensity; see "Tiling".',
    ],
    formula: 'I(matmul) = 2BDF / (2BD + 2DF + 2BF) ≈ B',
    sourceRef: 'reference/scaling-book/roofline.md — "Matrix multiplication"',
    related: ['critical-batch', 'arithmetic-intensity', 'compute-bound', 'tiling', 'systolic-array'],
  },
  {
    id: 'critical-batch',
    title: 'Critical Batch Size (B_crit)',
    summary: 'The per-replica token batch at which a matmul crosses the ridge and becomes compute-bound.',
    body: [
      'B_crit = I_hw = (Peak FLOPs/s) / (Bandwidth) for bf16 weights and math.',
      'Quantize weights to int8 but keep bf16 compute and B_crit halves (~120). Quantize both and B_crit returns to ~240 because FLOPs/s doubles.',
      'In general B_crit = β · α_hbm, where β = bits-per-param / bits-per-activation.',
      'During generation you reach this only by batching many concurrent requests together (each needs its own KV cache).',
      'Mixture-of-Experts inflates the critical batch by the sparsity factor E/k (ratio of total to activated params): compute-bound when B > 120·E/k. For DeepSeek v3 (k=8, E=256) that is an enormous B > 3840 tokens.',
      'B_crit is a per-replica token batch (tokens, not sequences): halving the number of chips per replica halves the effect, and it scales per independent copy of the weights.',
    ],
    formula: 'B_crit = β · (Peak FLOPs/s / Bandwidth),  β = bits/param ÷ bits/activation',
    sourceRef: 'reference/scaling-book/inference.md — "Linear operations: what bottlenecks us?"',
    related: ['matmul-intensity', 'quantization', 'generation', 'moe'],
  },
  {
    id: 'prefill',
    title: 'Prefill',
    summary: 'Processing a long prompt all at once; linear ops reuse weights across many tokens, so it is compute-bound.',
    body: [
      'Prefill processes a long prompt of T tokens in one pass and saves the key/value projections into a KV cache.',
      'Linear ops reuse their weights across B·T tokens, and attention intensity is ≈ T/2, so prefill is almost always compute-bound for real prompts.',
      'Maximizing hardware utilization directly improves Time-To-First-Token (TTFT).',
      'Roofline-wise, prefill looks almost identical to training.',
      'During prefill, attention is itself compute-bound for most real prompts — attention intensity ≈ T/2, which is above the ridge once the sequence exceeds roughly 480 tokens.',
      'Because prefill has a real sequence dimension, all the training sharding strategies (model, sequence, pipeline, FSDP) are viable for it — including sequence/context parallelism.',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "The Basics of Transformer Inference"',
    related: ['generation', 'kv-cache', 'compute-bound'],
  },
  {
    id: 'generation',
    title: 'Generation',
    summary: 'Sampling one token at a time against the KV cache; weights are not amortized, so it is almost always memory-bound.',
    body: [
      'Generation runs one token at a time (T = 1). Weights are not reused across tokens — each step streams the full parameter set plus its own KV cache.',
      'Attention intensity ST/(S+T) ≈ 1 (constant), far below the ridge, so attention is always memory-bandwidth-bound.',
      'Batching many concurrent requests is what pushes per-token intensity back toward the ridge during generation.',
      'The step-time bound: T_step ≥ (B·KV-cache + parameters) / bandwidth for small generate batches.',
      'Attention during generation has intensity ≈ ST/(S+T) ≈ 1 — a small constant, far below the ridge — so attention is always memory-bandwidth-bound during decode; see "Attention Intensity".',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "What about attention?"',
    related: ['prefill', 'kv-cache', 'memory-bound', 'latency-throughput'],
  },
  {
    id: 'kv-cache',
    title: 'KV Cache',
    summary: 'Stored key/value projections that let generation avoid reprocessing past tokens — and the dominant memory cost in inference.',
    body: [
      'A token only attends to previous tokens, so we cache each token\'s key and value projections and reuse them instead of reprocessing the prefix.',
      'KV cache size = 2 · bytes per float · H · K · L · T. It can be enormous: a single 8k sequence on LLaMA-13B is ~6.7 GB at bf16.',
      'The KV cache is the main reason generation is memory-bound and why techniques like GQA, quantization, and paged attention matter.',
      'Per token the cache costs 2 · L · K · H bytes (L layers, K KV heads, H head dim) — e.g. LLaMA-3-70B needs ≈160 kB/token at int8 and ≈324 kB/token at bf16, so a long context × large batch quickly grows into terabytes.',
      'System-level tricks shrink it: GQA/MQA, quantization, local attention windows, layer sharding, and paged/allocation approaches can cut KV memory by over an order of magnitude.',
    ],
    formula: 'KV-cache size = 2 · (bytes/float) · H · K · L · T',
    sourceRef: 'reference/scaling-book/transformers.md — "Key-Value (KV) caching"',
    related: ['generation', 'gqa', 'memory-bound', 'paged-attention', 'local-attention', 'kv-sharding'],
  },
  {
    id: 'gqa',
    title: 'GQA / Multi-Query Attention',
    summary: 'Sharing KV heads across query heads to shrink the KV cache and raise attention arithmetic intensity.',
    body: [
      'Normal MHA gives every query head its own KV head. GQA shares a smaller number of KV heads across many query heads (down to a single one in MQA).',
      'This shrinks the KV cache by the Q:KV head ratio, which helps fit bigger batches and longer contexts, and improves attention intensity.',
      'LLaMA-3 uses 32 query heads but only 8 KV heads.',
      'Concretely, a 1:5 GMQA on LLaMA-2-13B (40 query heads shared over 8 KV heads) makes the KV cache 5x smaller, letting a batch of 64 fit and lifting throughput at BS=240 from ~963 to ~4,529 tokens/s.',
      'Sharing KV heads barely costs model quality while raising attention arithmetic intensity — one of the cheapest wins in inference.',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "Tricks for Improving Generation Throughput and Latency"',
    related: ['kv-cache', 'generation'],
  },
  {
    id: 'latency-throughput',
    title: 'Latency vs Throughput',
    summary: 'The core inference tradeoff: small batches are fast per request but waste hardware; big batches are efficient but slower.',
    body: [
      'Inference introduces latency (Time-To-First-Token and per-token latency) that training does not care about.',
      'Small generate batches give low per-token latency but poor hardware utilization; large batches give high throughput (tokens/s) but higher latency and more KV memory.',
      'Supporting a bigger batch usually requires a bigger topology (more chips / KV capacity).',
      'The theoretical max tokens/s = (B×Bandwidth) / (B×KV-cache + parameters).',
    ],
    formula: 'Max tokens/s = (B × BW) / (B × KVcache + Params)',
    sourceRef: 'reference/scaling-book/inference.md — "Theoretical estimates for LLM latency and throughput"',
    related: ['generation', 'critical-batch', 'tco'],
  },
  {
    id: 'network-roofline',
    title: 'Inter-Chip (Network) Roofline',
    summary: 'When a model is sharded across chips, the bottleneck can shift from HBM bandwidth to the inter-chip network — set by model dimension D, not batch B.',
    body: [
      'Two chips splitting the contracting D dimension each do B·D·F FLOPs and exchange 2·B·F bytes of partial sums.',
      'The inter-chip intensity is I = BDF / (2BF) = D/2 — it depends on the model dimension D, not the batch B.',
      'With a network bandwidth of 4.5e10 bytes/s and 1.97e14 FLOPs/s per chip, you are compute-bound when D/2 > 4377, i.e. D > 8755, regardless of batch.',
      'Bandwidths differ by link: on-chip HBM (~1-2 TB/s) > inter-chip ICI (~90 GB/s per axis) > PCIe (~16 GB/s) > data-center network DCN (~6.25 GB/s). The network roofline uses whichever link the data actually crosses.',
      'This is why model parallelism during generation is bounded by the model dimension D, not the token batch B — see "Model Parallelism for Generation".',
    ],
    formula: 'I(2-chip) = BDF / (2BF) = D/2',
    sourceRef: 'reference/scaling-book/roofline.md — "Network communication rooflines"',
    related: ['roofline', 'matmul-intensity', 'collectives'],
  },
  {
    id: 'quantization',
    title: 'Quantization & β',
    summary: 'Lowering bytes-per-parameter changes arithmetic intensity and the critical batch size.',
    body: [
      'Quantization changes intensity by changing bytes-per-parameter, and changes how many FLOPs/s the accelerator can sustain.',
      'int8/fp8 weights with bf16 compute halve the weight bytes while FLOPs stay bf16 → B_crit ≈ I_hw/2. This is the easy win.',
      'int8 weights AND int8 math roughly double FLOPs/s → B_crit returns to ~base; the two effects cancel.',
      'It is governed by β = bits-per-param / bits-per-activation.',
      'Quantization can be applied post-training, since inference is more tolerant of low precision than training — and it helps both weights and the KV cache.',
      'Going further to int4/fp8 keeps the win compounding: int4 weights let LLaMA-3-70B fit on a TPU v5e 2x2 and roughly double queries/chip vs int8.',
      'Batch-specific (per-token) weights break the pattern: when every batch element needs a different matrix, comms explode to BD + BDF + BF and intensity collapses to a constant ≈2 — such an op is always communication-bound.',
    ],
    formula: 'B_crit = I_hw · β',
    sourceRef: 'reference/scaling-book/inference.md — "Linear operations: what bottlenecks us?"',
    related: ['critical-batch', 'matmul-intensity'],
  },
  {
    id: 'tco',
    title: 'Total Cost of Ownership (TCO)',
    summary: 'Running a model costs electricity plus amortized hardware — and it interacts with batch size and utilization.',
    body: [
      'TCO ≈ Electricity (Joules × PUE × cost/kWh) + Hardware amortized over a period at a given utilization.',
      'PUE (Power Usage Effectiveness) captures cooling overhead; liquid-cooled systems can reach PUE near 1.05.',
      'Cost per token falls with larger batches until diminishing returns as the KV cache grows.',
      'A practical procurement lens is FLOPs per dollar: at Google Cloud pricing (Feb 2025) the TPU v5e ($1.2/hr, 1.97e14 FLOPs/s) delivers ≈5.8e17 FLOPs/$ — the best of H100, v5p, and v5e — but the right pick depends on whether you are bandwidth- or compute-limited.',
      'MFU (actual vs peak FLOPs) matters as much as the price tag: two chips with equal FLOPs/$ differ in cost per token by their realized utilization.',
      'Unique to inference: serving throughput (queries or tokens/sec per dollar) and TTFT are first-class costs, not just total FLOPs.',
    ],
    sourceRef: 'reference/scaling-book/applied-inference.md — "Visualizing the Latency Throughput Tradeoff"',
    related: ['latency-throughput', 'generation', 'mfu', 'flops-per-token'],
  },
  {
    id: 'model-parallelism',
    title: 'Model Parallelism for Generation',
    summary: 'During generation you prefer variants of model parallelism — move activations, not weights or KV caches.',
    body: [
      'FSDP is unviable for generation: it moves weights over the network, which is far slower than HBM. We want to move activations instead.',
      'Pure data parallelism is also unhelpful in generation — it replicates parameters without helping load them faster.',
      'The main options are model parallelism, plus sharding the KV cache along heads then batch to keep it distributed.',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "Distributing Inference Over Multiple Accelerators"',
    related: ['network-roofline', 'generation', 'kv-cache', 'kv-sharding', 'tensor-parallelism', 'fsdp', 'collectives'],
  },
  {
    id: 'memory-hierarchy',
    title: 'Memory Hierarchy & On-Chip Memory',
    summary: 'HBM is big and slow; VMEM/SMEM on the chip is small but ~22x faster — and it decides the achievable arithmetic intensity.',
    body: [
      'An accelerator has two memory tiers that matter for rooflines: HBM (large, off-chip, ~1-2 TB/s) and on-chip memory (VMEM on TPUs, SMEM/TMEM on GPUs) that sits right next to the math units.',
      'VMEM is ~22x higher bandwidth than HBM. As a result a matrix-unit op only needs arithmetic intensity of ~10-20 to hit peak FLOPs when fed from VMEM, versus ~240 when fed from HBM.',
      'The GPU hierarchy is analogous but deeper: HBM → L2 → L1/SMEM → TMEM → registers; SMEM plays the same role as VMEM (~256 kB SMEM per SM, ~128 MiB VMEM on a TPU v5e).',
      'Compute happens only after data is copied from HBM into on-chip memory — this copy is exactly the "communication" that the roofline charges for.',
    ],
    sourceRef: 'reference/scaling-book/tpus.md — "VMEM and arithmetic intensity" · reference/scaling-book/gpus.md — "Memory"',
    related: ['bandwidth', 'tiling', 'roofline', 'flops'],
  },
  {
    id: 'mfu',
    title: 'Model FLOPs Utilization (MFU)',
    summary: 'The fraction of peak FLOPs/s a workload actually achieves — the bridge from theoretical math time to wall-clock time.',
    body: [
      'MFU = achieved FLOPs/s ÷ peak FLOPs/s. Real time is T = FLOPs / (chips · C · MFU), so MFU is the single biggest correction to raw FLOPs math.',
      'Typical values: GPUs reach ~80-85% of claimed peak on dense matmuls, TPUs closer to ~95%; end-to-end transformers are lower — LLaMA-3 exemplifies ~45-50%, and DeepSeek v3 achieved only ~21.7% (measured from H800 hours on 14.8T tokens).',
      'You can read MFU off a roofline plot: an op on the flat "compute roof" has high MFU; one deep in the sloped bandwidth region wastes FLOPs and has low MFU.',
    ],
    formula: 'T = FLOPs / (chips · C · MFU)',
    sourceRef: 'reference/scaling-book/training.md — "Fully-Sharded Data Parallelism (FSDP)"',
    related: ['flops', 'roofline', 'flops-per-token'],
  },
  {
    id: 'tiling',
    title: 'Tiling & On-Chip Reuse',
    summary: 'Large matmuls are cut into tiles that fit on-chip memory and re-loaded, which lowers effective intensity to ≈ bm·bn/(bm+bn).',
    body: [
      'A big matmul is decomposed into tiles that fit in higher-bandwidth on-chip memory (VMEM/SMEM/TMEM) rather than streaming everything from HBM.',
      'Because tiles are loaded multiple times, actual bytes exceed the naive O(N²) estimate, and effective arithmetic intensity becomes ≈ bm·bn/(bm+bn) for tile dimensions bm × bn.',
      'Tiling also forces padding (e.g. an f32[3,5] tiled by T(2,2) pads to [4,6], ~1.6x memory), and XLA inserts copies to re-layout tensors — all overhead roofline analysis must account for.',
      'So "tuning the tile size" is really tuning arithmetic intensity — a lever the pure B-based rules abstract away.',
    ],
    formula: 'I(tiled) ≈ bm·bn / (bm + bn)',
    sourceRef: 'reference/scaling-book/roofline.md — "Matrix multiplication" · reference/scaling-book/profiling.md — "How to read an XLA op"',
    related: ['matmul-intensity', 'memory-hierarchy', 'arithmetic-intensity', 'systolic-array'],
  },
  {
    id: 'flops-per-token',
    title: 'FLOPs per Token',
    summary: 'A model needs about 6·N FLOPs per token to train and 2·N per forward inference pass — the basis of most cost math.',
    body: [
      'Training spends 6·N FLOPs per token: 2·N in the forward pass plus 4·N in the backward pass (the "6× rule"). A single forward/inference pass is only 2·N.',
      'For LLaMA-3-70B that is ≈4.2e11 FLOPs/token, or ~0.4 TFLOP per token — and on one v5p chip at perfect utilization that is ~1 ms/token of pure math.',
      'This makes it trivial to estimate training time: total FLOPs = 6·N·tokens, then divide by (chips · C · MFU).',
    ],
    formula: 'FLOPs/token ≈ 6·N (train) · 2·N (infer-forward)',
    sourceRef: 'reference/scaling-book/applied-training.md — "Counting parameters and FLOPs"',
    related: ['flops', 'mfu', 'tco'],
  },
  {
    id: 'collectives',
    title: 'Collectives: AllGather / ReduceScatter / AllReduce / AllToAll',
    summary: 'The four communication primitives for sharded models, with cost ≈ bytes ÷ bandwidth — independent of chip count.',
    body: [
      'When a tensor is sharded across chips, reshaping or reducing it needs a collective: AllGather (replicate), ReduceScatter (sum then shard), AllReduce (= ReduceScatter + AllGather), AllToAll (move data between axes).',
      'Throughput-bound cost depends only on array size and bandwidth, not on the number of devices: AllGather/ReduceScatter ≈ V/W, AllReduce ≈ 2V/W, AllToAll ≈ V/(4W).',
      'Small arrays are different: each interconnect hop has ~1 µs overhead, so anything under ~45 kB (TPU v5e ICI) is latency-bound and stops scaling with bandwidth.',
      'AllReduce = AllGather + ReduceScatter, and the transpose of AllGather is ReduceScatter — which is exactly why backward passes can reuse forward comms.',
    ],
    formula: 'T = V/W (AG/RS), 2V/W (AR), V/4W (A2A)',
    sourceRef: 'reference/scaling-book/sharding.md — "A Deeper Dive into TPU Communication Primitives"',
    related: ['network-roofline', 'tensor-parallelism', 'fsdp', 'collective-matmul'],
  },
  {
    id: 'tensor-parallelism',
    title: 'Tensor Parallelism (Megatron)',
    summary: 'Shard the weight matrices and activations across chips; every layer needs an AllGather + ReduceScatter, which ride the critical path.',
    body: [
      'In tensor (model) parallelism the activations are sharded along d_model and the weights along d_ff; before each up-projection you AllGather the activations and after the down-projection you ReduceScatter.',
      'Unlike data parallelism, these collectives are on the critical path — they cannot be hidden asynchronously.',
      'It is comms-bound when the sharding degree Y exceeds F/(C/W_ici) ≈ F/2550 on a TPU v5p; for most models that lands around 8-16 way.',
      'During generation, where weights must be reloaded every step, variants of model parallelism are the only viable option (see "Model Parallelism for Generation").',
    ],
    sourceRef: 'reference/scaling-book/training.md — "Tensor Parallelism"',
    related: ['collectives', 'fsdp', 'model-parallelism', 'network-roofline'],
  },
  {
    id: 'fsdp',
    title: 'FSDP & ZeRO',
    summary: 'Split optimizer state, gradients, and weights across data-parallel chips to fit huge models — budget 10 bytes per parameter in training.',
    body: [
      'FSDP (Full-Sharded Data Parallelism, aka ZeRO-3) shards the optimizer state, gradients, and weights across the data-parallel axis and gathers/scatters them just in time, instead of replicating everything on every chip.',
      'Training a bf16 model with an fp32 Adam optimizer costs 10 bytes per parameter (2 bytes weights + 8 bytes optimizer state), so a 96 GB v5p chip fits at most ~9B parameters under pure DP.',
      'Both DP and FSDP are compute-bound only when the per-device token batch B/X exceeds the interconnect intensity C/W_ici (≈2550 on a v5p) — below that they are communication-bound.',
      'FSDP moves weights over the network, so it is unusable for memory-bound generation; there you prefer tensor/activation parallelism.',
    ],
    sourceRef: 'reference/scaling-book/training.md — "Fully-Sharded Data Parallelism (FSDP)"',
    related: ['tensor-parallelism', 'collectives', 'model-parallelism', 'data-parallelism', 'training-memory'],
  },
  {
    id: 'sequence-parallelism',
    title: 'Sequence / Context Parallelism',
    summary: 'Data-parallel over the token dimension too — used in prefill, where attention needs a gather of KV/query.',
    body: [
      'Sequence (context) parallelism treats tokens as just another batch dimension: the MLP happily data-parallels over both batch and sequence tokens.',
      'Attention is the wrinkle — it computes across sequences, so KV/query blocks must be gathered (typically via ring attention) while math and comms overlap.',
      'It only makes sense for prefill, where a real long sequence exists; generation has no sequence dimension to shard, which is why generation uses model parallelism instead.',
    ],
    sourceRef: 'reference/scaling-book/training.md — "Data Parallelism" · reference/scaling-book/inference.md — "Prefill"',
    related: ['prefill', 'collectives', 'tensor-parallelism', 'ring-attention'],
  },
  {
    id: 'pipeline-parallelism',
    title: 'Pipeline Parallelism',
    summary: 'Split layers across chips and stream microbatches; extremely cheap communication but prone to a "pipeline bubble".',
    body: [
      'Pipeline parallelism shards the model along the layer dimension: each stage does some layers, then passes activations (forward) and gradients (backward) to the next.',
      'Communication is tiny (just activations), which is why it dominates on GPUs.',
      'Its cost is idle time: while the pipeline fills and drains, stages sit idle — the "pipeline bubble". Microbatching (many small batches) plus overlapping forward/dLdx/dLdW matmuls shrinks the bubble.',
      'DeepSeek v3 published a "bubble-free" schedule that prioritizes backward dL/dx matmuls to keep every stage busy.',
    ],
    sourceRef: 'reference/scaling-book/training.md — "Pipelining"',
    related: ['tensor-parallelism', 'fsdp'],
  },
  {
    id: 'collective-matmul',
    title: 'Collective Matmul (Overlap)',
    summary: 'Overlap a matmul\'s communication with compute by tiling and starting reductions early — hiding comms almost entirely.',
    body: [
      'The idea (Wang et al. 2023): while computing one chunk of a sharded matmul, start the ring reduction for the previous chunk, so interconnect traffic runs behind math.',
      'It directly targets the overlap window from the lower/upper bound — when T_math ≈ T_comms, hiding comms wins the most.',
      'Measured on TPU: a naive blocking-AllGather matmul took ~311 µs, the overlapped collective matmul ~244 µs, versus an unsharded baseline of ~224 µs — nearly free communication.',
    ],
    sourceRef: 'reference/scaling-book/sharding.md — "How to overlap matmul communication with compute"',
    related: ['overlap', 'collectives', 'tensor-parallelism'],
  },
  {
    id: 'ttft',
    title: 'Time to First Token (TTFT)',
    summary: 'The latency before a request\'s first token — an inference-only metric that batched prefill makes worse.',
    body: [
      'Training only cares about throughput; inference adds two latency goals: TTFT and per-token latency.',
      'Batching many prefills together delays TTFT, because a user sees nothing until their prefill finishes — so aggressive prefill batching trades TTFT for throughput.',
      'Maximizing hardware utilization (MFU) directly shortens TTFT, but unlike training it does not necessarily improve any single user\'s experience.',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "What do we actually want to optimize?"',
    related: ['latency-throughput', 'prefill', 'continuous-batching'],
  },
  {
    id: 'continuous-batching',
    title: 'Continuous Batching',
    summary: 'An orchestrator prefills requests of different lengths and generates all active ones together, so short jobs are not blocked by long ones.',
    body: [
      'Naive batch-then-generate leaves short generations waiting on long ones; continuous batching fixes this by compiling a prefill function for variable context lengths and a generate function for all active requests.',
      'An orchestrator queues incoming requests, calls prefill when a generation slot frees, inserts the new KV cache, and streams generated tokens.',
      'It pairs with prefix caching: requests sharing a prefix reuse cached KV instead of re-prefilling.',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "Continuous batching"',
    related: ['ttft', 'prefix-caching', 'latency-throughput'],
  },
  {
    id: 'disaggregated-serving',
    title: 'Disaggregated Prefill/Generate',
    summary: 'Run prefill and generation on separate server pools, shipping KV caches over the network to keep both fully utilized.',
    body: [
      'Prefill and generation have opposite rooflines (compute-bound vs memory-bound) and ideal hardware, so serving them on separate TPU/GPU pools lets each be specialized.',
      'A request is prefilled on one server, its KV cache is sent over the network, and generation continues elsewhere — so no request blocks another and prefill servers need not hold KV caches.',
      'The tradeoff: KV caches must cross the network, which is why smaller KV caches (GQA, quantization) make disaggregation cheaper. For LLaMA-70B bf16 the prefill:generate server ratio works out to ≈3:1 (P = 3G).',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "Designing an Effective Inference Engine"',
    related: ['prefill', 'generation', 'prefix-caching', 'kv-cache'],
  },
  {
    id: 'prefix-caching',
    title: 'Prefix Caching',
    summary: 'Autoregressive models recompute identical KV for shared prompt prefixes — so cache the prefix and skip re-prefill.',
    body: [
      'Because LLMs are autoregressive, two queries that share a prefix ("I like dogs" / "I like cats") compute identical KV for the shared tokens; reusing that cache avoids that prefill compute.',
      'This is powerful for chatbots (appending turns) and few-shot/system prompts, and is typically stored as an LRU trie with LRU eviction.',
      'Caches can live in unused prefill-server HBM or CPU host DRAM (e.g. ~450 GiB on an 8xTPU v5e) — too slow for generation but fine for cache reads.',
      'Smaller KV caches compound the win because more prefixes fit in the same memory.',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "Prefix caching"',
    related: ['prefill', 'kv-cache', 'continuous-batching'],
  },
  {
    id: 'speculative-decoding',
    title: 'Speculative Decoding',
    summary: 'A small draft model proposes K tokens; the big model verifies them in one batched forward — more tokens per step for the same math.',
    body: [
      'A cheap draft model generates K candidate tokens; the large target model then scores them all in a single batched forward pass.',
      'It wins on latency because generation is not compute-bound: the big model is doing memory-bound work anyway, so verifying extra tokens is nearly "free" FLOPs — you get more tokens out per step.',
      'Greedy decoding keeps the longest correct prefix and resamples the first wrong token; non-greedy uses a Metropolis-Hastings-style accept/reject on draft-vs-target probabilities (so the distribution is unchanged).',
      'For a Chinchilla-70B + 4B drafter the ideal speculation length is ~3-4 tokens on summarization, more on code.',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "Appendix D: Speculative Sampling"',
    related: ['generation', 'ttft', 'latency-throughput'],
  },
  {
    id: 'paged-attention',
    title: 'Paged / Paged Attention',
    summary: 'Store KV caches in OS-style page tables and read them non-contiguously, so every batch uses only the memory it needs.',
    body: [
      'Raggged (variable-length) KV reads waste memory on padding; paged attention stores KV in fixed-size pages addressed via a page table, like virtual memory.',
      'Each generation step attends to a set of pages and touches only the pages that exist — avoiding loading/storing padding.',
      'It is a runtime/allocator optimization (PagedAttention, arXiv 2309.06180) independent of model architecture, and it pairs with long-context serving.',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "Tricks for Improving Generation Throughput and Latency"',
    related: ['kv-cache', 'generation', 'memory-bound'],
  },
  {
    id: 'attention-intensity',
    title: 'Attention Arithmetic Intensity',
    summary: 'Attention intensity is ST/(S+T): ~T/2 (compute-bound) at prefill, but ≈1 (always memory-bound) during generation.',
    body: [
      'Attention moves 4BSD + 4BTD bytes (Q, K, V reads and O write) for 4BSTD FLOPs, giving intensity I = ST/(S+T).',
      'Prefill (S = T) has intensity ≈ T/2, which grows with sequence length — so attention is compute-bound for any prompt longer than ~480 tokens.',
      'Generation (T = 1, S large) has intensity ≈ 1 — a small constant far below the ridge — so decode attention is always memory-bandwidth-bound and no optimization fixes that.',
      'This asymmetry is why prefill and generation need different treatments everywhere in inference.',
    ],
    formula: 'I(attn) = ST/(S+T) · prefill ≈ T/2 · generation ≈ 1',
    sourceRef: 'reference/scaling-book/inference.md — "What about attention?"',
    related: ['prefill', 'generation', 'attention-flops'],
  },
  {
    id: 'flash-attention',
    title: 'Flash Attention',
    summary: 'Compute attention in on-chip chunks with running max/O/L statistics, never materializing the full [B,S,T] attention matrix.',
    body: [
      'Standard attention would write an O(B·S·T) attention matrix to HBM; flash attention instead processes K/V in chunks that fit VMEM, keeping running max M, output O, and denominator L.',
      'Chunks combine via L_comb = exp(M_discrepancy)·L1 + exp(...)·L2, preserving exact softmax across arbitrary-length sequences with constant memory.',
      'Because chunks stay on-chip it raises attention\'s arithmetic intensity and makes large-context prefill affordable (a single 8k activation is only ~80 MB).',
      "It also enables sequence-block-local backward (ring attention) by swapping a contraction along the long key dimension for a local one along depth.",
    ],
    sourceRef: 'reference/scaling-book/transformers.md — "Appendix A: How does Flash Attention work?"',
    related: ['attention-intensity', 'memory-hierarchy', 'sequence-parallelism', 'ring-attention'],
  },
  {
    id: 'local-attention',
    title: 'Local Attention Layers',
    summary: 'Mask attention to a diagonal window so each layer only sees a bounded context — cap the KV cache for long sequences.',
    body: [
      'Instead of attending to the whole prefix, a layer can attend only to tokens within a fixed window (a diagonal strip of the attention matrix).',
      'Interleaving local layers with global layers caps the KV cache length for the local layers, greatly shrinking KV memory at contexts longer than the window.',
      'It trades a little modeling capacity for a big reduction in KV memory and bandwidth — a common ingredient in long-context models alongside GQA.',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "Tricks for Improving Generation Throughput and Latency"',
    related: ['kv-cache', 'attention-intensity', 'gqa'],
  },
  {
    id: 'moe',
    title: 'Mixture-of-Experts (MoE)',
    summary: 'Route each token through k of E experts: many more parameters, only a few active — which shifts both memory and the critical batch.',
    body: [
      'An MoE replaces each dense MLP with E independent MLPs and a router that activates k per token (k ≪ E); sparsity = E/k is typically 8-64 (DeepSeek v3: k=8, E=256).',
      'Total parameters grow by ~E while activated (used) parameters per token grow by only k — so memory cost is high but active FLOPs stay moderate.',
      'That sparsity inflates the generation critical batch: compute-bound requires B > 120·E/k, which for DeepSeek is B > 3840 tokens — a remarkably large serving batch.',
      'MoE needs an AllToAll to route tokens to the right experts, which is why it interacts with sharding and the network roofline.',
    ],
    sourceRef: 'reference/scaling-book/transformers.md — "Sparsity and Mixture-of-Experts"',
    related: ['critical-batch', 'kv-cache', 'collectives', 'quantization'],
  },
  {
    id: 'attention-flops',
    title: 'Attention vs Matmul FLOPs',
    summary: 'Attention is only a large share of FLOPs once the sequence exceeds ~8D tokens — usually attention is the small part.',
    body: [
      'Per layer, MLP matmul FLOPs dominate attention as long as T < 8D: the attention-to-matmul FLOPs ratio is ≈ T/8D.',
      'Attention only overtakes the matmuls once T > 8D (equivalently 2D ≈ T). For a model with D ≈ 8k that crossover is around 64k tokens; Gemma-27B (D=4608) crosses near ~37k.',
      'So for typical context lengths you are almost always matmul-limited in FLOPs — but attention still dominates memory (KV cache) during generation.',
    ],
    formula: 'Attn/Mx FLOPs ≈ T/8D · attention dominant when T > 8D',
    sourceRef: 'reference/scaling-book/transformers.md — "Fractional cost of attention with context length"',
    related: ['attention-intensity', 'flops', 'kv-cache'],
  },
  {
    id: 'expert-parallelism',
    title: 'Expert Parallelism',
    summary: 'Shard MoE experts across chips and route tokens to them with AllToAll — each token only touches the experts it needs.',
    body: [
      'With E experts but only k active per token, replicating all experts on every chip wastes memory; expert parallelism shards the weight along the expert dimension as [E_Z, D, F].',
      'Routing tokens to the right chips costs two AllToAlls per MoE block (before and after); each AllToAll is ~1/4 of a comparable AllGather.',
      'Feasibility depends on the feed-forward size F versus the interconnect: small F works within 1-2 nodes; large F can span arbitrarily many (up to E-way).',
    ],
    sourceRef: 'reference/scaling-book/gpus.md — "Expert Parallelism"',
    related: ['moe', 'collectives', 'network-roofline'],
  },
  {
    id: 'scaling',
    title: 'Strong vs Weak Scaling',
    summary: 'The goal of "model scaling": double the chips and get (roughly) double the throughput — until communication takes over.',
    body: [
      'The goal of model scaling is to increase the number of chips while achieving a proportional, roughly linear increase in throughput — this is "strong scaling".',
      'Performance on a single chip is set by the trade-off between memory bandwidth and FLOPs; performance at the cluster level depends on hiding inter-chip communication by overlapping it with useful math.',
      'Adding parallel chips usually shrinks per-device compute but adds communication between chips. When that communication takes longer than the remaining computation, the model is "communication-bound" and can no longer scale strongly.',
      'The same logic applies when you hold per-chip batch constant and grow the model instead (weak scaling): the comms load grows faster than the compute you have to hide it with.',
      'Each parallelism scheme below (data, tensor, pipeline, expert) has a crossover batch/dimension at which it stops scaling — the core subject of the training and inference chapters.',
    ],
    sourceRef: 'reference/scaling-book/index.md — "High-Level Outline" · reference/scaling-book/training.md — "What Do We Mean By Scaling?"',
    related: ['data-parallelism', 'tensor-parallelism', 'pipeline-parallelism', 'network-roofline', 'compute-bound'],
  },
  {
    id: 'data-parallelism',
    title: 'Data Parallelism',
    summary: 'Replicate weights on every chip, shard activations along the batch, and AllReduce gradients on the backward pass.',
    body: [
      'Pure data parallelism splits activations across the batch dimension and keeps an identical copy of all weights (and optimizer state) on every device. The forward pass needs no communication at all.',
      'All the communication happens on the backward pass: each chip AllReduces its local gradients at the end of every step to keep the replicated weights in sync.',
      'These AllReduces are not on the critical path — they can be done asynchronously — which makes DP the most forgiving scheme. It only becomes communication-bound when the per-device batch B/X drops below the ICI operational intensity C/W_ici.',
      'Computing that bound for TPU v5p (C = 4.6e14 FLOPs/s, W = 2·9e10 bytes/s over a 1D mesh) gives B/X > 2550; using all three mesh axes 3x the bandwidth and drops it to BS ≈ 850 per chip — roughly 7.6M tokens per pod. So pure DP is rarely the bottleneck.',
      'Its weakness is memory: because weights are replicated, the model is capped by HBM/10 parameters (weights + fp32 optimizer state), about 9B on a 96 GB v5p chip (see "Memory per Parameter").',
      'Rule of thumb: if a model fits on one chip with a compute-bound batch (B > 240), always use simple data parallelism first.',
    ],
    formula: 'compute-bound (DP) iff B/X > C/W_ici  ·  max params = HBM / 10',
    sourceRef: 'reference/scaling-book/training.md — "Data Parallelism"',
    related: ['fsdp', 'training-memory', 'scaling', 'collectives', 'critical-batch'],
  },
  {
    id: 'training-memory',
    title: 'Memory per Parameter (10-byte Rule)',
    summary: 'Training a bf16 model with an fp32 Adam optimizer costs ~10 bytes per parameter (weights + optimizer state), capping model size on a chip.',
    body: [
      'To train you must hold the parameters, gradients, and optimizer state in memory. With bf16 parameters and an fp32 Adam optimizer (which stores first and second moment accumulators), that is 2 + 8 = 10 bytes per parameter.',
      'So the largest model pure data parallelism can fit is (HBM per device) / 10 parameters — on a 96 GB TPU v5p chip that is roughly 9B parameters.',
      'If you keep fp32 weights instead of bf16, the total becomes 16 bytes per parameter (4 bytes weights + 12 bytes optimizer state), halving capacity again.',
      'These are lower bounds that ignore activation checkpoints, which can dwarf parameter memory during training (a 4M-token × 64-layer × D=8192 model needs ~84 TB of activations if none are discarded; see "Gradient Checkpointing").',
      'This is why optimizer/weight sharding (FSDP/Zeo) and rematerialization are essential for real training runs.',
    ],
    formula: 'Metadata bytes/param ≈ 10 (bf16 weights + fp32 Adam) · 16 (fp32 weights)',
    sourceRef: 'reference/scaling-book/training.md — "Data Parallelism" · reference/scaling-book/inference.md — "What about memory?"',
    related: ['fsdp', 'data-parallelism', 'remat', 'memory-hierarchy'],
  },
  {
    id: 'remat',
    title: 'Gradient Checkpointing / Rematerialization',
    summary: 'Trade compute for memory by re-running the forward pass during backward instead of storing every activation.',
    body: [
      'Backprop avoids O(layers²) compute but needs O(layers) memory to save every intermediate activation from the forward pass — and that is enormous: a 4M-token, 64-layer, D=8192 model would hold roughly 2·20·B·T·D·L ≈ 84 TB of bf16 activations (the 20 counts intermediate nodes per layer).',
      '"Block remat" saves only the input to each layer (1 checkpoint per layer), cutting that to ~4.2 TB but forcing a re-run of the forward pass during backward — raising per-token FLOPs from roughly 6·params to 8·params.',
      '"Big matmuls only" saves just the outputs of large matmuls, avoiding recomputing them while still recomputing activations and part of attention; this drops the ~20 intermediates per layer to closer to 7.',
      'In JAX these policies are controlled by jax.remat / jax.checkpoint. Rematerialization is one of the main reasons memory rarely binds pre-training.',
    ],
    formula: 'FLOPs/token: 6·N → ~8·N with aggressive block remat',
    sourceRef: 'reference/scaling-book/transformers.md — "Gradient checkpointing"',
    related: ['training-memory', 'mfu', 'flops-per-token', 'memory-hierarchy'],
  },
  {
    id: 'host-offload',
    title: 'Host (CPU) Offloading',
    summary: 'Move rarely-needed weights, optimizer state, or cached prefixes to CPU DRAM over PCIe — slow but nearly unbounded.',
    body: [
      'The CPU host connects to accelerator HBM over PCIe at only ~16 GB/s each way (TPU v4) — close to 100x slower than HBM. You can offload data to the host\'s RAM, but not very quickly.',
      'This is fine for data you seldom touch: optimizer state and stale gradients in training, or shared/prefix KV caches and infrequently used weights in inference.',
      'Prefix caches can live in unused prefill-server HBM or host DRAM (~450 GiB on an 8xTPU v5e) — too slow to feed generation, but fine for one-time cache reads during prefill.',
      'Because the offload link is so slow, offloading the parameter stream that generation reloads every step would destroy throughput — which is why generation never host-offloads its weights.',
    ],
    sourceRef: 'reference/scaling-book/tpus.md — "What Is a TPU?" (PCIe) · reference/scaling-book/inference.md — "Prefix caching"',
    related: ['prefix-caching', 'memory-hierarchy', 'tco', 'tpu-architecture'],
  },
  {
    id: 'gradient-accumulation',
    title: 'Gradient Accumulation',
    summary: 'Accumulate gradients over several small microbatches to emulate a much larger effective batch without extra activation memory.',
    body: [
      'Gradient accumulation averages gradients across many microbatches before updating weights, so you can train with a large effective batch even when individual microbatches are tiny.',
      'It is one of the standard "reduce memory" techniques (alongside rematerialization, optimizer/weight sharding, and host offload) that let you side-step activation and optimizer memory limits.',
      'The effective per-device batch still matters for the roofline: to stay compute-bound with data parallelism you need B/X > C/W_ici, so accumulated micro-batches should be sized to keep the effective batch above that crossover.',
      'It trades step time for memory: each microbatch redoes the full forward and backward, so more accumulation steps means more total FLOPs for the same optimizer step.',
    ],
    sourceRef: 'reference/scaling-book/index.md — "High-Level Outline" · reference/scaling-book/training.md — "Data Parallelism"',
    related: ['data-parallelism', 'training-memory', 'critical-batch'],
  },
  {
    id: 'tpu-architecture',
    title: 'TPU Architecture (TensorCore)',
    summary: 'A TPU is a matrix-multiplication core (MXU) plus a vector unit (VPU), an on-chip scratchpad (VMEM), and big slow HBM.',
    body: [
      'A TPU chip is basically a TensorCore specialized for matrix multiply attached to a stack of High-Bandwidth Memory (HBM, tens of GB, ~1-2 TB/s, ~16 GiB on v5e).',
      'The TensorCore has three key units: the MXU (matrix-multiply unit, a systolic array doing bf16[8,128]@bf16[128,128]→f32[8,128] every 8 cycles, ~5e13 FLOPs/s per MXU), the VPU (vector unit for pointwise ops, activations, and reductions), and VMEM (a small on-chip scratchpad, 128 MiB on v5e, with ~22x HBM\'s bandwidth to the MXU).',
      'TPUs are fast at matmul precisely because matmul uses O(n³) compute for O(n²) bytes, letting the ALUs stay compute-bound rather than bandwidth-bound.',
      'All operations are pipelined and overlapped: data streams HBM → VMEM → MXU/VPU → VMEM → HBM, which keeps the MXU fed and matmuls compute-bound even below the nominal ridge.',
      'A chip often holds two cores sharing memory (a "megacore" on v4/v5/v6); v6e and v7 differ (256x256 MXU, high-bandwidth inter-core link), and inference chips like v5e have a single core.',
    ],
    sourceRef: 'reference/scaling-book/tpus.md — "What Is a TPU?"',
    related: ['systolic-array', 'memory-hierarchy', 'bandwidth', 'flops', 'tpu-networking'],
  },
  {
    id: 'systolic-array',
    title: 'Systolic Array (MXU)',
    summary: 'The 2D grid of multiply-add ALUs at the heart of the MXU — weights stream top-down, activations stream left-to-right.',
    body: [
      'The MXU is a 2D grid of ALUs — 128x128 (= 16,384) on most TPUs, 256x256 on v6e — each doing one multiply-and-add per cycle.',
      'Weights (RHS) enter on one edge and activations (LHS) on another; each ALU multiplies the overlapping values, adds the partial sum passed from above, and passes the result downward.',
      'There is an initial pipeline bubble while the array fills, but afterwards new inputs and weights load without an extra bubble — so it stays efficient on large, well-tiled matmuls.',
      'To use the array fully your tiled dimensions must exceed 128 x (number of MXUs) — 128 for v3, 256 for v4/v5 — and Trillium\'s 256x256 array needs tiles twice as large to saturate.',
      'This is why weights are streamed repeatedly from HBM (or better, prefetched into VMEM) for reuse across many activation chunks.',
    ],
    sourceRef: 'reference/scaling-book/tpus.md — "Appendix B: How does a systolic array work?"',
    related: ['tpu-architecture', 'tiling', 'matmul-intensity'],
  },
  {
    id: 'tpu-networking',
    title: 'TPU Networking (ICI, Torus, DCN)',
    summary: 'Chips connect via ICI in low-dimensional tori; big pods and slow data-center links (DCN) sit above.',
    body: [
      'TPUs connect to their nearest neighbors through ICI (inter-chip interconnect): 4 neighbors forming a 2D torus on v2/v3/v5e/v6e, 6 neighbors forming a 3D torus on v4/v5p. These links never pass through the host.',
      'The torus cuts the max distance between nodes from N to N/2; a "twisted torus" wraps it like a Möbius strip to shrink average distance further.',
      'Pods can be huge: v4 superpods reach 16x16x16, v5p 16x20x28, built from reconfigurable 4x4x4 cubes joined by optical wraparound links. Small slices (e.g. 2x2x1) have no wraparound and roughly double comms overhead.',
      'Running bandwidth on v5p: ~2.8e12 bytes/s HBM vs ~9e10 bytes/s ICI per axis (3 axes) vs ~6.25e9 bytes/s DCN egress per chip. ICI is fast but still ~30x slower than HBM, and DCN is ~15x slower than ICI.',
      'Different ICI-connected groups are "slices"; slices link over slower DCN (host-to-host), so buffers cross PCIe twice. TPUs scale to huge topologies with constant per-device bandwidth and links — cheaper than GPU switching fabrics (see GPUs).',
    ],
    sourceRef: 'reference/scaling-book/tpus.md — "TPU Networking"',
    related: ['network-roofline', 'collectives', 'scaling', 'tensor-parallelism'],
  },
  {
    id: 'kv-sharding',
    title: 'Sharding the KV Cache',
    summary: 'Distribute the KV cache across chips along heads then batch — avoiding the memory-bandwidth cost of reloading it every step.',
    body: [
      'During distributed generation the KV cache is the primary source of attention latency, so we almost always shard it rather than replicate it.',
      'First shard the keys/values along the head dimension (limited to K-way sharding). For models with few KV heads, continue sharding along the batch dimension: KV[2, B_Z, S, K_Y, H] so the whole cache is distributed.',
      'This costs two AllToAlls per attention layer — one to move Q activations from model sharding to batch sharding so they can act on the KVs, and one to move the attention output back.',
      'For long contexts or small batches, sequence-shard the KV cache instead, paying a collective cost to accumulate attention across shards (AllGather the Qs, then accumulate KVs like Flash Attention).',
      'Sharded KVs stay stationary in on-chip memory, which is exactly what keeps generation memory-bandwidth-bound from dominating latency.',
    ],
    sourceRef: 'reference/scaling-book/inference.md — "Sharding the KV cache"',
    related: ['kv-cache', 'generation', 'model-parallelism', 'collectives', 'gqa'],
  },
  {
    id: 'ring-attention',
    title: 'Ring Attention',
    summary: 'Data-parallel over the sequence dimension by gathering KV/query blocks along a ring while overlapping math with communication.',
    body: [
      'Tokens are just another batch dimension as far as the MLP is concerned, so context/sequence parallelism treats the sequence like batch — except attention crosses sequences.',
      'Ring attention handles this by gathering the required KV (or query) blocks along a ring and overlapping the gather with local FLOPs, instead of materializing the full attention matrix.',
      'It is the standard vehicle for sequence/context parallelism during prefill, and it also enables Flash Attention\'s sequence-block-local backward by swapping the long-key contraction for a local one along depth.',
      'It only makes sense where a real sequence exists (prefill); generation has no sequence dimension to shard, which is why it uses model parallelism instead.',
    ],
    sourceRef: 'reference/scaling-book/training.md — "Data Parallelism" (context parallelism note) · reference/scaling-book/transformers.md — "Appendix A: How does Flash Attention work?"',
    related: ['sequence-parallelism', 'flash-attention', 'collectives', 'prefill'],
  },
  {
    id: 'linear-attention',
    title: 'Linear Attention (Gated DeltaNet)',
    summary: 'A recurrent attention: instead of storing a growing per-token KV cache, each layer keeps a fixed-size hidden state that is updated in place.',
    body: [
      'Transformer "linear attention" replaces the quadratic attention matrix with a recurrent state. Gated DeltaNet keeps a per-layer state matrix of fixed size (V heads × head_dim) and updates it in place each step — the size does NOT grow with context length.',
      'That is the critical serving consequence: memory for the attention state is constant per sequence regardless of prompt or total output length. A dense MHA/GQA model pays 2·bytes·heads·dim·layers·tokens per token; DeltaNet pays it once.',
      'Because the state is fixed, linear-attention layers also read/write a constant amount per decode step, which keeps short-token decode latency low and removes the KV-growth wall that dominates long-context inference.',
      'The tradeoff: linear attention is less expressive than full attention, which is why production models pair it with a small number of full (or sparse) attention layers rather than replacing attention entirely.',
    ],
    formula: 'KV_state size = 2 · bytes · V_heads · head_dim · layers (constant, not × tokens)',
    sourceRef: 'Qwen/Qwen3.8-Flash-Next model card — "Gated DeltaNet" (huggingface.co/Qwen/Qwen3.8-Flash-Next)',
    related: ['kv-cache', 'sparse-attention', 'generation', 'memory-bound'],
  },
  {
    id: 'sparse-attention',
    title: 'Sparse Attention (QSA)',
    summary: 'Attention where each query only looks at a bounded budget of key/value positions chosen by a lightweight indexer, instead of the whole key space.',
    body: [
      'Qwen Sparse Attention (QSA) operates at the micro-block level: a cheap indexer picks a fixed budget of blocks (e.g. 512 blocks ≈ 2048 tokens) that each query may attend to, rather than every position in a 262k+ token context.',
      'The KV a layer must read per decode step is bounded by the budget, not by the full context. This collapses both the KV-memory footprint and the attention latency of very long contexts — the dominant cost for agentic workloads.',
      'It is the sparse-attention half of the hybrid design: the Gated DeltaNet layers provide constant-size recurrent state, and the occasionally-inserted QSA layers add the flexible, long-range attention that a pure linear model lacks.',
      'From a roofline view, sparse attention keeps the "KV read" term in the decode memory clock capped, so long-context serving does not grow unboundedly toward memory-bound.',
    ],
    formula: 'attention KV read / step ≈ budget (blocks), independent of total context',
    sourceRef: 'Qwen/Qwen3.8-Flash-Next model card — "Qwen Sparse Attention" (huggingface.co/Qwen/Qwen3.8-Flash-Next)',
    related: ['linear-attention', 'kv-cache', 'local-attention', 'attention-intensity'],
  },
  {
    id: 'n-gram-embedding',
    title: 'N-gram Embedding',
    summary: 'Scaling parameters as lookups keyed by short n-grams (bigrams/trigrams) rather than by MoE experts — cheap per-token compute and easy to offload.',
    body: [
      'Qwen3.8-Flash-Next scales a large chunk of its parameters (51B) as n-gram embeddings: rather than routing through MoE experts, text is indexed by short n-gram keys and looked up in embedding tables inserted at layer 2.',
      'The compute cost is a low-cost gather (lookup + add), not a full matmul per token, so these parameters add representational capacity with far less inference FLOPs than an equivalent dense or MoE block.',
      'Unlike expert weights that must be resident to route correctly, the n-gram tables are more amenable to offloading (e.g. to CPU/host) when HBM is tight, trading bandwidth for capacity.',
      'This is why the headline "6B activated" can coexist with a much larger resident model: the 51B embedding terms contribute almost none of the per-token FLOPs.',
    ],
    formula: 'per-token cost ≈ gather(lookup) + add, not 2·params·tokens FLOPs',
    sourceRef: 'Qwen/Qwen3.8-Flash-Next model card — "N-gram Embedding" (huggingface.co/Qwen/Qwen3.8-Flash-Next)',
    related: ['moe', 'memory-bound', 'flops-per-token', 'host-offload'],
  },
  {
    id: 'attention-params',
    title: 'Multi-Head Attention (QKVO) Math',
    summary: 'Attention is four projections — Q, K, V, then O — whose FLOPs and parameters are easy to count.',
    body: [
      'Grouped-query attention has N query heads, K KV heads, and head dim H. The four linear projections (Q, K, V, O) dominate attention parameters and FLOPs.',
      'Per-layer training FLOPs: Q and O are 6BTDNH each, K and V are 6BTDKH each; parameters total 2D(N+K)H. With N = K (full MHA) that is 12BTDNH FLOPs and 4DNH params.',
      'The dot-product attention itself is a TH·HS matmul over the B,K dims plus a softmax, roughly 12BTSNH ≈ 12BT²NH FLOPs (halved by a causal mask if you use an attention kernel).',
      'Unembedding and layernorms are separate: two layernorms per layer cost only O(BTD) with 2D params — negligible for first-order estimates; the final unembedding matmul is 6BTDV with DV params.',
      'Counting all layer FLOPs (18BTDF for the two MLP matmuls times three for training) recovers the rule of thumb: total ≈ 6 · params · tokens.',
    ],
    formula: 'Attn params = 2D(N+K)H · FLOPs(train) ≈ 12BTD(N+K)H',
    sourceRef: 'reference/scaling-book/transformers.md — "Attention" · "Other Operations"',
    related: ['attention-intensity', 'attention-flops', 'flops-per-token', 'gqa'],
  },
];

export const CONCEPT_MAP: Record<string, Concept> = Object.fromEntries(
  CONCEPTS.map((c) => [c.id, c])
);

export function getConcept(id: string): Concept | undefined {
  return CONCEPT_MAP[id];
}
